---
title: "Tijdlijn Reoadmap Toetsen op afstand"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r, echo=FALSE}
# Import data
data.file <- read.csv("Roadmap.csv", header = T)
data.file$Thema        <- gsub('\\[|\\]|\\"', "", data.file$Thema)
data.file$Stakeholders <- gsub('\\[|\\]|\\"', "", data.file$Stakeholders)
data.file$Thema        <- gsub('\\%26', "&", data.file$Thema)
data.file$Stakeholders <- gsub('\\%26', "&", data.file$Stakeholders)
data.file$Stakeholders <- gsub(',', "<br>", data.file$Stakeholders)
```

## Tabel

```{r, echo=FALSE}
library("DT")

datatable(data.file[, c("Titel","Doel","Thema","Stakeholders","Resultaat")],
          rownames = FALSE,
          escape = FALSE)

```

## Tijdlijn

Tijdlijn van de activiteiten binnen de roadmap van de [werkgroep toetsen op afstand](https://versnellingsplan.nl/zones/toetsen-op-afstand/). 

```{r, echo=FALSE}
# Select relevant columns
# names(data.file)
data.file <- data.file[,c("Titel","Thema","Startdatum","Eind.datum", "Doel")]

# data.file
```


```{r, echo=FALSE}
# install.packages("timevis")
# https://github.com/daattali/timevis
library("timevis")

# rename columns

names(data.file) <- c("content", "group", "start", "end", "title")

data.file$id <- 1:dim(data.file)[1]

# Assign date class
data.file$start <- as.Date(data.file$start, "%d-%m-%Y")
data.file$end   <- as.Date(data.file$end,   "%d-%m-%Y")

themes <- data.frame(number = 1:length(unique(data.file$group)),
                     theme  = unique(data.file$group))

data.file <- merge(data.file, themes, by.x = "group", by.y = "theme")

themes[6, 2] = "Overig"

data.file$group <- as.integer(data.file$number)

# Rename themes
names(themes) <- c("id", "content")

themes$content[2] = "Toetsdoel & toetsontwerp"

timevis(data.file[,c(-7)],
        groups = themes,
        # options = list(width = "900px")
        )
```





